application: haowaiwai-01
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  mime_type: image/x-icon
  
- url: /.*
  script: helloworld.app