/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jeecms_core_util_JavaCallDll */

#ifndef _Included_com_jeecms_core_util_JavaCallDll
#define _Included_com_jeecms_core_util_JavaCallDll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jeecms_core_util_JavaCallDll
 * Method:    EncodeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jeecms_core_util_JavaCallDll_EncodeFile
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_jeecms_core_util_JavaCallDll
 * Method:    DecodeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jeecms_core_util_JavaCallDll_DecodeFile
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
